version : "1.0"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: metadata_api
    ports:
      - 5004:5004
    environment:
      MONGO_URI: mongodb://root:root@mongo:27017/metadata_inventory?authSource=admin
      MONGO_DB: metadata_inventory
    depends_on:
      mongo:
        condition: service_healthy
    restart: unless-stopped

  mongo:
    image: mongo
    container_name: inventory_mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 120s
      timeout: 30s
      retries: 5
      start_period: 10s

volumes:
  mongo_data: